name: AI Peer Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  
env:
  STANDARDS_REPO: https://github.com/clarencetinator7/coding-standards-poc

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js environment
        uses: actions/setup-node@v4

      - name: Checkout code
        uses: actions/checkout@v5

      # - name: Clone coding standards docs
      #   run: git clone $STANDARDS_REPO standard-docs
        
      - name: Install Github CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Install Copilot CLI
        run: npm install -g @github/copilot

      - name: Test Copilot CLI
        env:
          COPILOT_GITHUB_TOKEN: ${{ secrets.COPILOT_GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REVIEW_OUTPUT=$(copilot -p "Tell me the summary of this pull request ${{github.event.pull_request.number}}")
          gh pr comment ${{ github.event.pull_request.number }} -b "$REVIEW_OUTPUT"