name: AI Peer Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  
env:
  STANDARDS_REPO: https://github.com/clarencetinator7/coding-standards-poc.git

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js environment
        uses: actions/setup-node@v4

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Clone coding standards docs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git clone $STANDARDS_REPO standard-docs
        
      - name: Install Github CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Install Copilot CLI
        run: npm install -g @github/copilot
      
      - name: Get PR Diff
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr diff ${{ github.event.pull_request.number }} > pr_diff.txt

      - name: Run AI Review
        env:
          COPILOT_GITHUB_TOKEN: ${{ secrets.COPILOT_GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          GUIDELINES=$(cat standard-docs/ai/ai-peer-review-guidelines.md)
          REVIEW_OUTPUT=$(copilot -p "Review the following PR diff against these guidelines: $GUIDELINES. Here is the diff: $(cat pr_diff.txt)")
          gh pr comment ${{ github.event.pull_request.number }} -b "$REVIEW_OUTPUT"